name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Setup Fyne
      run: go get fyne.io/fyne/v2/cmd/fyne
      
    - name: Build
      run: go build .

    - name: Fyne Release
      run: fyne package -os windows -icon logo.png

    - uses: papeloto/action-zip@v1
      with:
        files: kqb-json-viewer.exe
        dest: kqb-json-viewer-windows-amd64.zip

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: kqb-json-viewer-windows-amd64.zip